kortix_version = 1

[project]
name = "Smoke"
description = ""

[runtime]
root = ".opencode"

[env]
required = []
optional = []

[[apps]]
slug = "test-site6"
name = "test-site6"
enabled = true
domains = []

[apps.source]
type = "git"
repo = "https://github.com/templatecookie/poco-html"
branch = "master"

[[apps]]
slug = "machine-built"
name = "machine-built"
enabled = true
domains = []

[apps.source]
type = "git"
repo = "https://github.com/Sm0k367/machine-built"
branch = "master"

[[connectors]]
slug = "github"
provider = "pipedream"
credential = "shared"
app = "github"
account = "default"
